cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_details, name="cart_details"),
    path('add', views.add_to_cart, name="add"),
    path('remove/<int:id>', views.remove_from_cart, name="remove"),
    path('clear/', views.clear_cart, name="clear")
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from store import views

app_name = 'store'

urlpatterns = [
    path('', views.ProductList.as_view(), name='product_list'),
    path('categories', views.CategoriesList.as_view(), name='categories_list'),
    path('product/<slug:slug>/', views.ProdcutDetails.as_view(),
         name='product_details'),
]

store/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False)
    slug = models.SlugField(unique=True, max_length=100, db_index=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_path(self):
        return reverse('store:product_list') + f'?category={self.id}'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=100, null=False, blank=False)
    slug = models.SlugField(unique_for_date='created')
    description = models.TextField(null=False, blank=False)
    price = models.IntegerField(null=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='media/products/%Y/%m/%d/', blank=True)
    availibility = models.BooleanField(null=False, default=True)

    class Meta:
        index_together = ('id', 'slug')
        ordering = ('-created',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:product_details', kwargs={'slug': self.slug})

store/views.py
from django.shortcuts import render
from django.views import generic
from store.models import Product, Category
from django_filters.views import FilterView
from store.filters import ProductFilter
from cart.forms import CartForm
from django.db.models import Count

# Create your views here.


class ProductList(FilterView):
    model = Product
    queryset = Product.objects.all()
    paginate_by = 20
    filterset_class = ProductFilter
    context_object_name = 'products'
    template_name = 'store/product_list.html'

    def get_queryset(self):
        qs = super().get_queryset()
        if 'category_slug' in self.kwargs:
            qs = qs.filter(category__slug=self.kwargs['category_slug'])
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class ProdcutDetails(generic.DetailView):
    model = Product
    template_name = 'store/product_details.html'
    context_object_name = 'product'

    def get_queryset(self):
        product = super().get_queryset()
        return product.select_related('category').annotate(
            total_purchases=Count('ordered'))


class CategoriesList(generic.ListView):
    template_name = 'store/categories_list.html'
    context_object_name = 'categories'
    queryset = Category.objects.all().annotate(num_products=Count('products'))

store/templates/store/categories_list.html
{% extends 'base.html' %} {% block title %} Categories {% endblock title %}
{%block content %}
<div class="row my-2">
  {% for c in categories %}
  <div class="col-lg-3 col-md-6 col-12 my-2 px-sm-2">
    <div class="card text-center">
      <div class="card-body">
        <h3 class="font-weight-light">
          <a href="{{ c.get_absolute_path }}">{{c.name}}</a>
        </h3>
      </div>
      <div class="card-footer">
        {{c.num_products}} Product{{c.num_products|pluralize}}
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock content %}

store/templates/store/product_details.html
{%extends 'base.html'%} {%load thumbnail%} {%load store_tags%} {% block title %}
{{product.name}} {% endblock title %} {%block content%}
<nav>
  <ol class="breadcrumb mt-2">
    <li class="breadcrumb-item">
      <a href="{{product.category.get_absolute_url}}">{{product.category}}</a>
    </li>
    <li class="breadcrumb-item active">{{product.name}}</li>
  </ol>
</nav>
<div class="row mt-2 mb-4">
  <div class="col-lg-4 col-md-6 col-12">
    <img
      src="{% thumbnail product.image 500x0 %}"
      alt="{{product.name}}"
      class="img-fluid mx-auto d-block"
    />
  </div>
  <div class="col-lg-8 col-md-6 col-12">
    <h2 class="mt-md-0 mt-2">{{product.name}}</h2>
    <h3 class="font-weight-light"> {{product.price}} VNĐ/1 Kg </h3>
    <h4>
      {% if product.availibility %}
      <span class="badge badge-success">Còn Hàng</span>
      {% else %}
      <span class="badge badge-danger">Hết hàng</span>
      {% endif %}
    </h4>
    <p>{{product.description}}</p>
    <p>
      Đã được mua bởi <b>{{product.total_purchases}}</b>
      khách hàng{{product.total_purchases|pluralize}}.
    </p>
    {% if user.is_authenticated %}
    {% if product.id in cart.keys %}
    <form action="{% url 'cart:add' %}" method="POST" style="max-width: 400px">
      {% csrf_token %}
      <input type="hidden" name="product_id" value="{{product.id}}">
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text">Số lượng</span>
        </div>
        <input
          type="number"
          min="1"
          name="quantity"
          value="{{cart|getattr:product.id}}"
          required="required"
          class="form-control"
        />
        <div class="input-group-append btn-group">
          <button class="btn btn-primary" type="submit">
            <i class="fa fa-cart-plus fa-lg mr-2"></i> Sửa
          </button>
          <a href="{% url 'cart:remove' product.id %}" class="btn btn-danger">
            <i class="fa fa-times fa-lg mr-2"></i> Xóa
          </a>
        </div>
      </div>
    </form>
    {% elif product.availibility %}
    <form method="POST" action="{% url 'cart:add' %}">
      {% csrf_token %}
      <input type="hidden" name="quantity" value="1" />
      <input type="hidden" name="product_id" value="{{product.id}}" />
      <button type="submit" class="btn btn-primary">
        <i class="fa fa-cart-plus fa-lg mr-2"></i> Thêm vào giỏ
      </button>
    </form>
    {% else %}
    <button class="btn btn-primary" disabled>
      <i class="fa fa-cart-plus fa-lg mr-2"></i> Thêm vào giỏ
    </button>
    {% endif %}
    {% else %}
    <a href="{% url 'login' %}" class="btn btn-primary" disabled>
      <i class="fa fa-sign-in fa-lg mr-2"></i> Đăng nhập để thêm vào giỏ
    </a>
    {% endif %}
  </div>
</div>
{%get_similar product.id product.price product.category %} {% endblock content%}

store/templates/store/product_list.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% load thumbnail %}
{%block title %}Store{% endblock title %}
{%block content %}
<div class="row mt-3">
  <div class="col-lg-3 col-md-6 col-12 mb-3">
    <div class="card card-body p-3 shadow-sm sticky-top">
      <h2>Bộ lọc</h2>
      <form class="filter-form">
        <input type="hidden" name="name" id="id_name"> <div id="div_id_category" class="form-group"> <label for="id_category" class="">
          Danh Mục
      </label> <div class=""> <select name="category" class="select form-control" id="id_category"> <option value="" selected>---------</option> <option value="3">Rau</option> <option value="2">Củ Quả</option> <option value="1">Trái Cây</option>

</select> </div> </div> <div id="div_id_price" class="form-group"> <label class="">
          Giá
      </label> <div class=""> <input type="text" name="price_min" class="textinput textInput" id="id_price_0">

-<input type="text" name="price_max" class="textinput textInput" id="id_price_1"> </div> </div>
        <button class="btn btn-info btn-block btn-sm" type="submit">
          Lọc
        </button>
      </form>
    </div>
  </div>
  <div class="col-lg-9 col-md-6 col-12">
    <h2 class="font-weight-light mb-2">Sản Phẩm</h2>
    <hr />
    <div class="row">
      {% for product in products %}
      <div class="col-lg-4 col-12 mb-2 px-sm-1">
        <div class="card shadow-sm h-100">
          <img
            src="{% thumbnail product.image 0x150 %}"
            alt="No Image"
            class="img-aspect p-2"
          />
          <div class="card-body">
            <h3 class="card-subtitle font-weight-light">
              <a href="{% url 'store:product_details' product.slug %}"
                >{{product.name}}</a
              >
            </h3>
            <h4 class="card-text">
              <span class="badge badge-warning">{{product.price}} VNĐ/1 Kg</span>
            </h4>
            <p class="card-text">{{product.description|truncatewords:23 }}</p>
          </div>
        </div>
      </div>
      {% empty %}
      <div class="col-12 text-center">
        <h3 class="font-weight-light my-4 py-4">Không tìm thấy sản phẩm.</h3>
      </div>
      {% endfor %}
    </div>
    {% if products|length != 0 %}
    <nav>
      {% with page_obj as page %}
      <div class="mt-2">
        <p class="my-2">
          Trang {{ page.number }} của {{ page.paginator.num_pages }}
        </p>
        <ul class="pagination">
          {% if page.has_previous %}
          <li class="page-item">
            <a href="?page={{ page.previous_page_number }}" class="page-link">
              Trước
            </a>
          </li>
          {% endif %}
          <li class="page-item active">
            <a class="page-link">{{ page.number }}</a>
          </li>
          {% if page.has_next %}
          <li class="page-item">
            <a href="?page={{ page.next_page_number }}" class="page-link">
              Tiếp
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
      {% endwith %}
    </nav>
    {% endif %}
  </div>
</div>
<script>
  document.querySelector("#div_id_price > div").className = "d-flex justify-space-between align-items-center";
  document.querySelectorAll("#div_id_price input").forEach((i) => {
    i.classList.add("form-control")
    i.style.minWidth = '10px'
  });
  document.querySelectorAll(".filter-form .form-control").forEach((i) => i.classList.add("form-control-sm"));
</script>
{% endblock content %}

store/templates/store/similar.html
{% load thumbnail %}
<h3 class="font-weight-light mb-0">Similar Products</h3>
<hr />
<div class="row my-2">
  {% for product in products %}
  <div class="col-lg-3 col-md-4 col-12">
    <div class="card shadow-sm h-100">
      <img
        src="{% thumbnail product.image 0x150 %}"
        alt="{{product.name}}"
        class="card-img-top img-aspect p-2"
      />
      <div class="card-body">
        <h4 class="card-subtitle font-weight-light mb-1">
          <a href="{{ product.get_absolute_url }}">{{product.name}}</a>
        </h4>
        <h5 class="mb-0">
          <span class="badge badge-warning">{{product.price}} VNĐ/1 Kg</span>
        </h5>
      </div>
    </div>
  </div>
  {% empty %}
  <div class="col-12">
    <h5 class="font-weight-light">No similar products found.</h5>
  </div>
  {% endfor %}
</div>